import re
import joblib

# ---- Load the exact same model + vectorizer saved by train_classifier.py ----
model = joblib.load("models/Transaction_Type_Classifier.jonlib")
vectorizer = joblib.load("models/tfidf_vectorizer.joblib")

# ---- Same normalization function used during training — MUST match exactly,
# otherwise we'd be testing the model on differently-shaped input than it
# was trained on, which would make any result meaningless. ----
def normalize_text(text):
    text = str(text).lower()
    text = re.sub(r"[اآأإ]", "ا", text)
    text = re.sub(r"ي", "ى", text)
    text = re.sub(r"ه", "ة", text)
    text = re.sub(r"[0-9]+", " ", text)
    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

# ---- Hand-written test sentences — NOT generated by any template in
# generate_data.py. Some deliberately use merchants/phrasing/sentence
# shapes the model has never seen, to genuinely test generalization
# rather than template-matching. ----
test_cases = [
    # (sms_text, expected_transaction_type)
    # Purchase
    ("Hey! Just a heads up, EGP 340 was spent on your Meta Visa card at Gourmet Egypt yesterday.", "Purchase"),
    ("قمت بالدفع بمبلغ 220 جنيه لصالح متجر بست واي عن طريق بطاقتك", "Purchase"),
    ("Your card was charged 89.50 EGP for a purchase at Zara Store on July 10", "Purchase"),
    ("تنبيه فوري: خصم 45.75 جنيه لصالح مطعم فيلفيت بتاريخ اليوم", "Purchase"),
    ("A charge of EGP 610 appeared on your account for an order at IKEA Cairo", "Purchase"),
    ("دفعت مبلغ 95 جنيه اونلاين لصالح تطبيق أوردر", "Purchase"),
    ("Your Visa card was used to pay 150 EGP at a pharmacy in Zamalek", "Purchase"),
    ("تم خصم قيمة اشتراكك الشهري في الجيم بمبلغ 500 جنيه", "Purchase"),
    ("EGP 78 was charged for a coffee order at an unlisted cafe downtown", "Purchase"),
    ("اشتريت هدية بقيمة 340 جنيه من محل هدايا في مدينتي", "Purchase"),

    # Salary Credit
    ("وصلك مبلغ 15000 جنيه في حسابك كراتب هذا الشهر، رصيدك الحالي أصبح 22000 جنيه", "Salary Credit"),
    ("Great news - your salary payment of EGP 18,200 just landed in your account", "Salary Credit"),
    ("راتبك الشهري وصل حسابك بمبلغ 9800 جنيه", "Salary Credit"),
    ("Your employer just deposited EGP 21,000 into your account as this month's pay", "Salary Credit"),
    ("تم صرف مرتبك لهذا الشهر وقيمته 12500 جنيه في حسابك البنكي", "Salary Credit"),
    ("Payroll deposit received: EGP 14,750 credited to your account today", "Salary Credit"),

    # ATM Withdrawal
    ("لقد قمت بسحب 500 جنيه نقدا من فرع البنك الرئيسي باستخدام بطاقتك", "ATM Withdrawal"),
    ("Withdrew EGP 1000 cash just now using your debit card", "ATM Withdrawal"),
    ("سحبت 300 جنيه من ماكينة صراف قريبة من المنزل", "ATM Withdrawal"),
    ("You just took out EGP 750 in cash from a branch machine", "ATM Withdrawal"),
    ("عملية سحب نقدي بقيمة 1200 جنيه تمت منذ قليل من فرع وسط البلد", "ATM Withdrawal"),
    ("Cash pulled from an ATM machine: EGP 600, using your Mastercard", "ATM Withdrawal"),

    # Transfer
    ("حولت لصديقك محمد مبلغ 750 جنيه عن طريق تطبيق البنك على موبايلك", "Transfer"),
    ("A payment of EGP 2,000 was sent from your account to another user via mobile banking", "Transfer"),
    ("أرسلت مبلغ 400 جنيه لأختك عن طريق إنستا باي", "Transfer"),
    ("You transferred EGP 1,300 to a friend using your banking app", "Transfer"),
    ("قمت بتحويل مبلغ 900 جنيه إلى حساب زميلك في العمل", "Transfer"),
    ("EGP 3,500 was sent out of your account to another beneficiary just now", "Transfer"),
    ("حولتلك فلوس الايجار 2200 جنيه على حساب صاحب الشقة", "Transfer"),
    ("Money transfer of EGP 500 completed to another bank account holder", "Transfer"),
]

correct = 0
print(f"{'Predicted':<16} {'Expected':<16} {'Match':<6} Text")
print("-" * 90)

for text, expected in test_cases:
    cleaned = normalize_text(text)
    vec = vectorizer.transform([cleaned])
    prediction = model.predict(vec)[0]
    is_correct = prediction == expected
    correct += is_correct
    mark = "✅" if is_correct else "❌"
    print(f"{prediction:<16} {expected:<16} {mark:<6} {text[:50]}")

print("-" * 90)
print(f"\nManual test accuracy: {correct}/{len(test_cases)} ({correct/len(test_cases)*100:.1f}%)")